### PR TITLE
Dont pass a done fn is the task is returnless/unnamed

### PR DESCRIPTION
**Pull request by KoryNunn**
@MauriceButler opinions?

### CODE REVIEW

**Comment by MauriceButler** [comment]
LGTM I dont think it is a huge deal as this wouldn't be used anyway but Major version is correct choice as is a breaking change

**Comment by MauriceButler** [comment]
[selfie-0](https://github.com/thieman/github-selfies/)

**Comment by KoryNunn** [comment]
I'll sit on this PR for a few days to make sure I'm happy with it, and because that pic has made me very unsettled.

**Comment by liamoehlman** [comment]
+1

**Comment by gbenvenuti** [comment]
+1

**Pull request merged**
